def image

pipeline 
{
    agent any

    stages 
    {
        stage( 'Build' )
        {
            steps
            {
                script
                {
                    image = docker.build( 'Simple_Flask_App/.' )
                }
            }
        }
        stage( 'Run Container' )
        {
            steps
            {
                script
                {
                    container = image.run()
                }
            }
        }
    }
    
}


