pipeline 
{
    agent
    {
      label 'docker-dotnetcore'
    }

    stages
    {
        stage('SCM')
        {
            steps
            {
                // Get some code from a GitHub repository
                git 'https://github.com/whayward-stfc/jenkins-test-applications'
            }
        }
        stage('Build')
        {
            steps
            {
                script
                {
                    try
                    {
                        sh 'dotnet build ConsoleApp1'
                    }
                    finally
                    {
                        archiveArtifacts artifacts: 'ConsoleApp1/*.*'
                    }
                }
            }
        }
    	stage('Test')
        {
    		echo 'Execute unit tests'
    	}
    	stage('Package')
        {
    		echo 'Zip it up'
    	}
    	stage('Deploy')
        {
    		echo 'Push to deployment'
    	}
    	stage('Archive')
        {
    		archiveArtifacts artifacts: 'ConsoleApp1/*.*'
    	}        
    }
}