pipeline 
{
    agent
    {
      label 'docker-dotnetcore'
    }

    stages
    {
        stage('SCM')
        {
            steps
            {
                // Get some code from a GitHub repository
                git 'https://github.com/whayward-stfc/jenkins-test-applications'
            }
        }
        stage('Build')
        {
            steps
            {
                dir('./Console_App_DNC')
                {
                    script
                    {
                        try
                        {
                            sh 'dotnet build ConsoleApp1'
                        }
                        finally
                        {
                            archiveArtifacts artifacts: 'ConsoleApp1/*.*'
                        }
                    }                    
                }
            }
        }
    	stage('Test')
        {
    		steps
            {
                echo 'Execute unit tests'
            }
    	}
    	stage('Package')
        {
    		steps
            {
                echo 'Zip it up'
            }
    	}
    	stage('Deploy')
        {
    		steps
            {
                echo 'Push to deployment'
            }
    	}
    	stage('Archive')
        {
            steps
            {
                dir('./Console_App_DNC')
                {
                    archiveArtifacts artifacts: 'ConsoleApp1/*.*'
                }

            }  
    	}        
    }
}